<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Concept" nsURI="http://www.semanticweb.org/ontologies/2011/1/TrainRequirementOntology.owl"
    nsPrefix="Concept">
  <eClassifiers xsi:type="ecore:EClass" name="Segment" eSuperTypes="#//Trackelement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Segment_length" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trackelement" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TrackElement_sensor" upperBound="-1"
        eType="#//Sensor" eOpposite="#//Sensor/Sensor_trackElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TrackElement_connectsTo"
        upperBound="-1" eType="#//Trackelement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Trackelement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Switch_actualState" lowerBound="1"
        eType="#//SwitchStateKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Switch_switchPosition"
        upperBound="-1" eType="#//SwitchPosition" eOpposite="#//SwitchPosition/SwitchPosition_switch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Route_entry" lowerBound="1"
        eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Route_switchPosition" upperBound="-1"
        eType="#//SwitchPosition" eOpposite="#//SwitchPosition/SwitchPosition_route"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Route_exit" lowerBound="1"
        eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Route_routeDefinition"
        lowerBound="2" upperBound="-1" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Signal_actualState" lowerBound="1"
        eType="#//SignalStateKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchPosition" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SwitchPosition_switch"
        lowerBound="1" eType="#//Switch" eOpposite="#//Switch/Switch_switchPosition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SwitchPosition_switchState"
        lowerBound="1" eType="#//SwitchStateKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SwitchPosition_route" lowerBound="1"
        eType="#//Route" eOpposite="#//Route/Route_switchPosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sensor_trackElement" upperBound="-1"
        eType="#//Trackelement" eOpposite="#//Trackelement/TrackElement_sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SignalStateKind">
    <eLiterals name="SignalStateKind_STOP"/>
    <eLiterals name="SignalStateKind_FAILURE" value="1"/>
    <eLiterals name="SignalStateKind_GO" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SwitchStateKind">
    <eLiterals name="PointStateKind_FAILURE"/>
    <eLiterals name="PointStateKind_LEFT" value="1"/>
    <eLiterals name="PointStateKind_RIGHT" value="2"/>
    <eLiterals name="PointStateKind_STRAIGHT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Thing" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
