language: java
jdk:
  - oraclejdk8
install: true
script:
  - git clone https://github.com/graphflow/graphflow
  - cd graphflow
  - ./gradlew publishToMavenLocal
  - cd ..
  - scripts/get-neo4j.sh
  - ./gradlew inits build --stacktrace --continue
notifications:
  slack: ldbcouncil:5g01hnE5LoES6n3K5jlsSesh
  email: false
  on_success: change
  on_failure: always
branches:
  except:
  - ingraph
