language: r
jdk:
  - oraclejdk8
install: false
script:
  - sudo service mysql restart
  - ./gradlew initScripts
  - ./gradlew build --exclude-task test
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
