sudo: required
language: python
jdk:
  - oraclejdk8
python:
  - "3.4"
script:
  - scripts/dep-mondo-sam.sh
  - scripts/dep-neo4j.sh
  - scripts/dep-allegro.sh
  - scripts/dep-virtuoso.sh
  - scripts/run.py --ci
