sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  -
script:
#  - scripts/init-config.sh
  - scripts/install-python.sh
  - pip3 freeze
#  - scripts/dep-mondo-sam.sh
#  - scripts/dep-graph.sh
  - scripts/run.py --build --skip-tests
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
