language: java
jdk:
  - oraclejdk8
install: true
script:
  - git clone https://github.com/graphflow/graphflow
  - cd graphflow
  - ./gradlew publishToMavenLocal
  - cd ..
  - scripts/get-neo4j.sh
  # excluding tests for the SQL generator as they require full control over a MySQL instance
  - ./gradlew inits build -x :trainbenchmark-generator-sql:test -x :trainbenchmark-tool-mysql:test --stacktrace --continue
notifications:
  slack: ldbcouncil:5g01hnE5LoES6n3K5jlsSesh
  email: false
  on_success: change
  on_failure: always
branches:
  except:
  - ingraph
