sudo: required
dist: trusty
language: groovy
jdk:
  - oraclejdk8
install:
  -
script:
  - scripts/dep-graph.sh
  - scripts/install.sh
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
