sudo: required
language: java
jdk:
  - oraclejdk8
install:
  -
script:
  - scripts/init-config.sh
  - scripts/init-python.sh
  - scripts/dep-mondo-sam.sh
  - scripts/dep-neo4j.sh
  - scripts/dep-virtuoso.sh
  - scripts/dep-iqdcore.sh
  - scripts/run.py --ci
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
