sudo: required
language: python
python:
  - "3.4"
script:
  - jdk_switcher use oraclejdk8
  - scripts/dep-mondo-sam.sh
  - scripts/dep-neo4j.sh
  - scripts/dep-allegro.sh
  - scripts/dep-incqueryd-core.sh
  - scripts/dep-virtuoso.sh
  - scripts/run.py --ci
