sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  -
script:
#  - scripts/init-config.sh
  - scripts/install-python.sh
#  - scripts/dep-mondo-sam.sh
#  - scripts/dep-graph.sh
  - python3 -c "import sys; print(sys.executable)"
  - sudo python3 -c "import sys; print(sys.executable)"
  - sudo -H python3 -c "import sys; print(sys.executable)"
  - python3 --version
  - python3 scripts/run.py --build --skip-tests
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
