sudo: required
dist: trusty
language: groovy
jdk:
  - oraclejdk8
install:
  -
script:
  - sudo service mysql restart
  - scripts/build.sh
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
