sudo: required
language: java
jdk:
  - oraclejdk8
script:
  - scripts/initialize.sh
  - scripts/dep-mondo-sam.sh
  - scripts/dep-neo4j.sh
  - scripts/dep-allegro.sh
  - scripts/dep-incqueryd-core.sh
  - scripts/dep-virtuoso.sh
  - scripts/run.py --ci
