language: java
jdk:
  - oraclejdk8
install: true
script:
  - scripts/get-neo4j.sh
  - ./gradlew inits build -x :trainbenchmark-generator-sql:test -x :trainbenchmark-tool-mysql:test
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
  email: false
  on_success: change
  on_failure: always
branches:
  except:
  - ingraph
