install.packages("ggplot2", repos="http://cran.rstudio.com/")
install.packages("jsonlite", repos="http://cran.rstudio.com/")
install.packages("devtools", repos="http://cran.rstudio.com/")
require(devtools)
install_version("plyr", version = "1.8.1", repos = "http://cran.rstudio.com/")
