allegro: rdf
blazegraph: rdf
drools5: emf
drools6: emf
eclipseocl: emf
emfapi: emf
emfincquery: emf
hawk: emf
iqdcore: rdf
jena: rdf
mysql: sql
neo4j: graph.neo4j
orientdb: graph.tinkerpop
postgresql: sql
sesame: rdf
sqlite: sql
tinkergraph: graph.tinkerpop
virtuoso: rdf
