PREFIX base: <http://www.semanticweb.org/ontologies/2011/1/TrainRequirementOntology.owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?xSegment1
WHERE
{
	?xSensor1 rdf:type base:Sensor .
	?xSensor2 rdf:type base:Sensor .
	?xSegment1 rdf:type base:Segment .
	?xSegment1 base:TrackElement_sensor ?xSensor1 .
	?xSegment2 rdf:type base:Segment .
	?xSegment3 rdf:type base:Segment .
	?xSegment4 rdf:type base:Segment .
	?xSegment5 rdf:type base:Segment .
	?xSegment6 rdf:type base:Segment .
	
	?xSegment1 base:TrackElement_connectsTo ?xSegment2 .
	?xSegment2 base:TrackElement_connectsTo ?xSegment3 .
	?xSegment3 base:TrackElement_connectsTo ?xSegment4 .
	?xSegment4 base:TrackElement_connectsTo ?xSegment5 .
	?xSegment5 base:TrackElement_connectsTo ?xSegment6 .
	?xSegment6 base:TrackElement_sensor ?xSensor2 .

	FILTER (?xSensor1 = ?xSensor2)
}
