PREFIX base: <http://www.semanticweb.org/ontologies/2011/1/TrainRequirementOntology.owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?xSensor
WHERE
{
	?xRoute rdf:type base:Route .
	?xSwitchPosition rdf:type base:SwitchPosition .
	?xSwitch rdf:type base:Switch .
	?xSensor rdf:type base:Sensor .
	?xRoute base:Route_switchPosition ?xSwitchPosition .
	?xSwitchPosition base:SwitchPosition_switch ?xSwitch .
	?xSwitch base:TrackElement_sensor ?xSensor .

	OPTIONAL {
		?xRoute ?xRoute_routeDefinition ?xSensor .
		FILTER (sameTerm(base:Route_routeDefinition, ?xRoute_routeDefinition))
	} .
	FILTER (!bound(?xRoute_routeDefinition))
}
