PREFIX base: <http://www.semanticweb.org/ontologies/2015/trainbenchmark#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?xSensor
WHERE
{
	?xRoute rdf:type base:Route .
	?xSwitchPosition rdf:type base:SwitchPosition .
	?xSwitch rdf:type base:Switch .
	?xSensor rdf:type base:Sensor .
	
	?xRoute base:follows ?xSwitchPosition .
	?xSwitchPosition base:switch ?xSwitch .
	?xSwitch base:sensor ?xSensor .

	OPTIONAL {
		?xRoute ?xDefinedBy ?xSensor .
		FILTER (sameTerm(base:definedBy, ?xDefinedBy))
	} .
	FILTER (!bound(?xDefinedBy))
}
