PREFIX base: <http://www.semanticweb.org/ontologies/2011/1/TrainRequirementOntology.owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?xRoute1
WHERE
{
	?xRoute1 base:Route_routeDefinition ?xSen1 .
	?xTE1 base:TrackElement_sensor ?xSen1 .
	?xTE1 base:TrackElement_connectsTo ?xTE2 .
	?xTE2 base:TrackElement_sensor ?xSen2 .
	?xRoute1 base:Route_exit ?xSig .

	?xRouteX base:Route_routeDefinition ?xSen2 .
	FILTER ( ?xRouteX != ?xRoute1 ) .

	OPTIONAL {
		?xRoute2 base:Route_entry ?xSig .
		?xRoute2 base:Route_routeDefinition ?xSen2 .
	} .
	FILTER (!bound(?xRoute2))	
}
