allegro: rdf
blazegraph: rdf
drools5: emf
drools6: emf
eclipseocl: emf
emfapi: emf
emfincquery: emf
hawk: emf
iqdcore: rdf
jena: rdf
mysql: sql
neo4j: graph
orientdb: graph
postgresql: sql
sesame: rdf
sqlite: sql
virtuoso: rdf
