--
-- Database: `trainbenchmark`
--

-- 512 Mb
SET max_heap_table_size=536870912;

DROP DATABASE IF EXISTS `trainbenchmark`;
CREATE DATABASE `trainbenchmark`;
USE `trainbenchmark`;

SET AUTOCOMMIT=0;
-- --------------------------------------------------------

--
-- Table structure: `Route`
--

CREATE TABLE IF NOT EXISTS `Route` (
  `id` int(11) NOT NULL auto_increment,
  `Route_entry` int(11) NOT NULL,
  `Route_exit` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `Route_routeDefinition`
--

CREATE TABLE IF NOT EXISTS `Route_routeDefinition` (
  `Route_id` int(11) NOT NULL,
  `Sensor_id` int(11) NOT NULL
) DEFAULT CHARSET=utf8 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `Segment`
--

CREATE TABLE IF NOT EXISTS `Segment` (
  `id` int(11) NOT NULL,
  `Segment_length` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `Sensor`
--

CREATE TABLE IF NOT EXISTS `Sensor` (
  `id` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `TrackElement_sensor`
--

CREATE TABLE IF NOT EXISTS `TrackElement_sensor` (
  `TrackElement_id` int(11) NOT NULL,
  `Sensor_id` int(11) NOT NULL
) DEFAULT CHARSET=utf8 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `Signal`
--

CREATE TABLE IF NOT EXISTS `Signal` (
  `id` int(11) NOT NULL auto_increment,
  `Signal_actualState` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `SignalStateKind`
--

CREATE TABLE IF NOT EXISTS `SignalStateKind` (
  `id` int(11) NOT NULL auto_increment,
  `text` varchar(32) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ENGINE=MEMORY;

--
-- Filling table `SignalStateKind`
--

INSERT INTO `SignalStateKind` (`id`, `text`) VALUES
(1, 'SignalStateKind_STOP'),
(2, 'SignalStateKind_FAILURE'),
(3, 'SignalStateKind_GO');

-- --------------------------------------------------------

--
-- Table structure: `Switch`
--

CREATE TABLE IF NOT EXISTS `Switch` (
  `id` int(11) NOT NULL,
  `Switch_actualState` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `SwitchPosition`
--

CREATE TABLE IF NOT EXISTS `SwitchPosition` (
  `id` int(11) NOT NULL auto_increment,
  `Route_switchPosition` int(11) NOT NULL,
  `SwitchPosition_switch` int(11) NOT NULL,
  `SwitchPosition_switchState` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `SwitchStateKind`
--

CREATE TABLE IF NOT EXISTS `SwitchStateKind` (
  `id` int(11) NOT NULL auto_increment,
  `text` varchar(32) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ENGINE=MEMORY;

--
-- Filling table `SwitchStateKind`
--

INSERT INTO `SwitchStateKind` (`id`, `text`) VALUES
(1, 'PointStateKind_FAILURE'),
(2, 'PointStateKind_LEFT'),
(3, 'PointStateKind_RIGHT'),
(4, 'PointStateKind_STRAIGHT');

-- --------------------------------------------------------

--
-- Table structure: `TrackElement`
--

CREATE TABLE IF NOT EXISTS `TrackElement` (
  `id` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=MEMORY;

-- --------------------------------------------------------

--
-- Table structure: `TrackElement_connectsTo`
--

CREATE TABLE IF NOT EXISTS `TrackElement_connectsTo` (
  `TrackElement_id` int(11) NOT NULL,
  `TrackElement_id_connectsTo` int(11) NOT NULL
) DEFAULT CHARSET=utf8 ENGINE=MEMORY;
INSERT INTO `Signal` (`id`, `Signal_actualState`) VALUES (1, 2);
INSERT INTO `Signal` (`id`, `Signal_actualState`) VALUES (2, 2);
INSERT INTO `Route` (`id`, `Route_entry`, `Route_exit`) VALUES (3, 0, 2);
INSERT INTO `TrackElement` VALUES (4);
INSERT INTO `Switch` (`id`) VALUES (4);
INSERT INTO `Sensor` (`id`) VALUES (5);
INSERT INTO `TrackElement_sensor` VALUES (4, 5);
INSERT INTO `Route_routeDefinition` VALUES (3, 5);
INSERT INTO `TrackElement` VALUES (6);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (6, 460);
INSERT INTO `TrackElement_sensor` VALUES (6, 5);
INSERT INTO `Sensor` (`id`) VALUES (7);
INSERT INTO `TrackElement_sensor` VALUES (4, 7);
INSERT INTO `Route_routeDefinition` VALUES (3, 7);
INSERT INTO `TrackElement` VALUES (8);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (8, 828);
INSERT INTO `TrackElement_sensor` VALUES (8, 7);
INSERT INTO `Sensor` (`id`) VALUES (9);
INSERT INTO `TrackElement_sensor` VALUES (4, 9);
INSERT INTO `Route_routeDefinition` VALUES (3, 9);
INSERT INTO `TrackElement` VALUES (10);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (10, 856);
INSERT INTO `TrackElement_sensor` VALUES (10, 9);
INSERT INTO `Sensor` (`id`) VALUES (11);
INSERT INTO `TrackElement_sensor` VALUES (4, 11);
INSERT INTO `TrackElement` VALUES (12);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (12, -136);
INSERT INTO `TrackElement_sensor` VALUES (12, 11);
INSERT INTO `Sensor` (`id`) VALUES (13);
INSERT INTO `TrackElement_sensor` VALUES (4, 13);
INSERT INTO `Route_routeDefinition` VALUES (3, 13);
INSERT INTO `TrackElement` VALUES (14);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (14, -978);
INSERT INTO `TrackElement_sensor` VALUES (14, 13);
INSERT INTO `Sensor` (`id`) VALUES (15);
INSERT INTO `TrackElement_sensor` VALUES (4, 15);
INSERT INTO `Route_routeDefinition` VALUES (3, 15);
INSERT INTO `TrackElement` VALUES (16);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (16, 812);
INSERT INTO `TrackElement_sensor` VALUES (16, 15);
INSERT INTO `Sensor` (`id`) VALUES (17);
INSERT INTO `TrackElement_sensor` VALUES (4, 17);
INSERT INTO `Route_routeDefinition` VALUES (3, 17);
INSERT INTO `TrackElement` VALUES (18);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (18, 126);
INSERT INTO `TrackElement_sensor` VALUES (18, 17);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 4;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (19, 2, 4, 3);
INSERT INTO `TrackElement` VALUES (20);
INSERT INTO `Switch` (`id`) VALUES (20);
INSERT INTO `Sensor` (`id`) VALUES (21);
INSERT INTO `TrackElement_sensor` VALUES (20, 21);
INSERT INTO `Route_routeDefinition` VALUES (3, 21);
INSERT INTO `TrackElement` VALUES (22);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (22, 644);
INSERT INTO `TrackElement_sensor` VALUES (22, 21);
INSERT INTO `Sensor` (`id`) VALUES (23);
INSERT INTO `TrackElement_sensor` VALUES (20, 23);
INSERT INTO `Route_routeDefinition` VALUES (3, 23);
INSERT INTO `TrackElement` VALUES (24);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (24, 640);
INSERT INTO `TrackElement_sensor` VALUES (24, 23);
INSERT INTO `Sensor` (`id`) VALUES (25);
INSERT INTO `TrackElement_sensor` VALUES (20, 25);
INSERT INTO `Route_routeDefinition` VALUES (3, 25);
INSERT INTO `TrackElement` VALUES (26);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (26, 851);
INSERT INTO `TrackElement_sensor` VALUES (26, 25);
INSERT INTO `Sensor` (`id`) VALUES (27);
INSERT INTO `TrackElement_sensor` VALUES (20, 27);
INSERT INTO `Route_routeDefinition` VALUES (3, 27);
INSERT INTO `TrackElement` VALUES (28);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (28, 366);
INSERT INTO `TrackElement_sensor` VALUES (28, 27);
INSERT INTO `Sensor` (`id`) VALUES (29);
INSERT INTO `TrackElement_sensor` VALUES (20, 29);
INSERT INTO `Route_routeDefinition` VALUES (3, 29);
INSERT INTO `TrackElement` VALUES (30);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (30, 628);
INSERT INTO `TrackElement_sensor` VALUES (30, 29);
INSERT INTO `Sensor` (`id`) VALUES (31);
INSERT INTO `TrackElement_sensor` VALUES (20, 31);
INSERT INTO `Route_routeDefinition` VALUES (3, 31);
INSERT INTO `TrackElement` VALUES (32);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (32, 541);
INSERT INTO `TrackElement_sensor` VALUES (32, 31);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 20;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (33, 0, 20, 3);
INSERT INTO `TrackElement` VALUES (34);
INSERT INTO `Switch` (`id`) VALUES (34);
INSERT INTO `Sensor` (`id`) VALUES (35);
INSERT INTO `TrackElement_sensor` VALUES (34, 35);
INSERT INTO `Route_routeDefinition` VALUES (3, 35);
INSERT INTO `TrackElement` VALUES (36);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (36, 233);
INSERT INTO `TrackElement_sensor` VALUES (36, 35);
INSERT INTO `Sensor` (`id`) VALUES (37);
INSERT INTO `TrackElement_sensor` VALUES (34, 37);
INSERT INTO `Route_routeDefinition` VALUES (3, 37);
INSERT INTO `TrackElement` VALUES (38);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (38, 420);
INSERT INTO `TrackElement_sensor` VALUES (38, 37);
INSERT INTO `Sensor` (`id`) VALUES (39);
INSERT INTO `TrackElement_sensor` VALUES (34, 39);
INSERT INTO `Route_routeDefinition` VALUES (3, 39);
INSERT INTO `TrackElement` VALUES (40);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (40, 891);
INSERT INTO `TrackElement_sensor` VALUES (40, 39);
INSERT INTO `Sensor` (`id`) VALUES (41);
INSERT INTO `TrackElement_sensor` VALUES (34, 41);
INSERT INTO `Route_routeDefinition` VALUES (3, 41);
INSERT INTO `TrackElement` VALUES (42);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (42, 208);
INSERT INTO `TrackElement_sensor` VALUES (42, 41);
INSERT INTO `Sensor` (`id`) VALUES (43);
INSERT INTO `TrackElement_sensor` VALUES (34, 43);
INSERT INTO `Route_routeDefinition` VALUES (3, 43);
INSERT INTO `TrackElement` VALUES (44);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (44, 435);
INSERT INTO `TrackElement_sensor` VALUES (44, 43);
INSERT INTO `Sensor` (`id`) VALUES (45);
INSERT INTO `TrackElement_sensor` VALUES (34, 45);
INSERT INTO `Route_routeDefinition` VALUES (3, 45);
INSERT INTO `TrackElement` VALUES (46);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (46, 152);
INSERT INTO `TrackElement_sensor` VALUES (46, 45);
INSERT INTO `Sensor` (`id`) VALUES (47);
INSERT INTO `TrackElement_sensor` VALUES (34, 47);
INSERT INTO `Route_routeDefinition` VALUES (3, 47);
INSERT INTO `TrackElement` VALUES (48);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (48, 339);
INSERT INTO `TrackElement_sensor` VALUES (48, 47);
INSERT INTO `Sensor` (`id`) VALUES (49);
INSERT INTO `TrackElement_sensor` VALUES (34, 49);
INSERT INTO `Route_routeDefinition` VALUES (3, 49);
INSERT INTO `TrackElement` VALUES (50);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (50, 192);
INSERT INTO `TrackElement_sensor` VALUES (50, 49);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 34;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (51, 0, 34, 3);
INSERT INTO `TrackElement` VALUES (52);
INSERT INTO `Switch` (`id`) VALUES (52);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 52;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (53, 0, 52, 3);
INSERT INTO `TrackElement` VALUES (54);
INSERT INTO `Switch` (`id`) VALUES (54);
INSERT INTO `Sensor` (`id`) VALUES (55);
INSERT INTO `TrackElement_sensor` VALUES (54, 55);
INSERT INTO `Route_routeDefinition` VALUES (3, 55);
INSERT INTO `TrackElement` VALUES (56);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (56, 691);
INSERT INTO `TrackElement_sensor` VALUES (56, 55);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 54;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (57, 2, 54, 3);
INSERT INTO `TrackElement` VALUES (58);
INSERT INTO `Switch` (`id`) VALUES (58);
INSERT INTO `Sensor` (`id`) VALUES (59);
INSERT INTO `TrackElement_sensor` VALUES (58, 59);
INSERT INTO `Route_routeDefinition` VALUES (3, 59);
INSERT INTO `TrackElement` VALUES (60);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (60, 272);
INSERT INTO `TrackElement_sensor` VALUES (60, 59);
INSERT INTO `Sensor` (`id`) VALUES (61);
INSERT INTO `TrackElement_sensor` VALUES (58, 61);
INSERT INTO `Route_routeDefinition` VALUES (3, 61);
INSERT INTO `TrackElement` VALUES (62);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (62, 136);
INSERT INTO `TrackElement_sensor` VALUES (62, 61);
INSERT INTO `Sensor` (`id`) VALUES (63);
INSERT INTO `TrackElement_sensor` VALUES (58, 63);
INSERT INTO `Route_routeDefinition` VALUES (3, 63);
INSERT INTO `TrackElement` VALUES (64);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (64, 632);
INSERT INTO `TrackElement_sensor` VALUES (64, 63);
INSERT INTO `Sensor` (`id`) VALUES (65);
INSERT INTO `TrackElement_sensor` VALUES (58, 65);
INSERT INTO `Route_routeDefinition` VALUES (3, 65);
INSERT INTO `TrackElement` VALUES (66);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (66, 585);
INSERT INTO `TrackElement_sensor` VALUES (66, 65);
INSERT INTO `Sensor` (`id`) VALUES (67);
INSERT INTO `TrackElement_sensor` VALUES (58, 67);
INSERT INTO `Route_routeDefinition` VALUES (3, 67);
INSERT INTO `TrackElement` VALUES (68);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (68, 84);
INSERT INTO `TrackElement_sensor` VALUES (68, 67);
INSERT INTO `Sensor` (`id`) VALUES (69);
INSERT INTO `TrackElement_sensor` VALUES (58, 69);
INSERT INTO `Route_routeDefinition` VALUES (3, 69);
INSERT INTO `TrackElement` VALUES (70);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (70, 245);
INSERT INTO `TrackElement_sensor` VALUES (70, 69);
INSERT INTO `Sensor` (`id`) VALUES (71);
INSERT INTO `TrackElement_sensor` VALUES (58, 71);
INSERT INTO `Route_routeDefinition` VALUES (3, 71);
INSERT INTO `TrackElement` VALUES (72);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (72, 374);
INSERT INTO `TrackElement_sensor` VALUES (72, 71);
INSERT INTO `Sensor` (`id`) VALUES (73);
INSERT INTO `TrackElement_sensor` VALUES (58, 73);
INSERT INTO `Route_routeDefinition` VALUES (3, 73);
INSERT INTO `TrackElement` VALUES (74);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (74, 17);
INSERT INTO `TrackElement_sensor` VALUES (74, 73);
INSERT INTO `Sensor` (`id`) VALUES (75);
INSERT INTO `TrackElement_sensor` VALUES (58, 75);
INSERT INTO `Route_routeDefinition` VALUES (3, 75);
INSERT INTO `TrackElement` VALUES (76);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (76, -558);
INSERT INTO `TrackElement_sensor` VALUES (76, 75);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 58;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (77, 1, 58, 3);
INSERT INTO `TrackElement` VALUES (78);
INSERT INTO `Switch` (`id`) VALUES (78);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 78;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (79, 1, 78, 3);
INSERT INTO `TrackElement` VALUES (80);
INSERT INTO `Switch` (`id`) VALUES (80);
INSERT INTO `Sensor` (`id`) VALUES (81);
INSERT INTO `TrackElement_sensor` VALUES (80, 81);
INSERT INTO `Route_routeDefinition` VALUES (3, 81);
INSERT INTO `TrackElement` VALUES (82);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (82, 892);
INSERT INTO `TrackElement_sensor` VALUES (82, 81);
INSERT INTO `Sensor` (`id`) VALUES (83);
INSERT INTO `TrackElement_sensor` VALUES (80, 83);
INSERT INTO `Route_routeDefinition` VALUES (3, 83);
INSERT INTO `TrackElement` VALUES (84);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (84, 144);
INSERT INTO `TrackElement_sensor` VALUES (84, 83);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 80;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (85, 3, 80, 3);
INSERT INTO `TrackElement` VALUES (86);
INSERT INTO `Switch` (`id`) VALUES (86);
INSERT INTO `Sensor` (`id`) VALUES (87);
INSERT INTO `TrackElement_sensor` VALUES (86, 87);
INSERT INTO `Route_routeDefinition` VALUES (3, 87);
INSERT INTO `TrackElement` VALUES (88);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (88, 545);
INSERT INTO `TrackElement_sensor` VALUES (88, 87);
INSERT INTO `Sensor` (`id`) VALUES (89);
INSERT INTO `TrackElement_sensor` VALUES (86, 89);
INSERT INTO `Route_routeDefinition` VALUES (3, 89);
INSERT INTO `TrackElement` VALUES (90);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (90, -823);
INSERT INTO `TrackElement_sensor` VALUES (90, 89);
INSERT INTO `Sensor` (`id`) VALUES (91);
INSERT INTO `TrackElement_sensor` VALUES (86, 91);
INSERT INTO `Route_routeDefinition` VALUES (3, 91);
INSERT INTO `TrackElement` VALUES (92);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (92, 607);
INSERT INTO `TrackElement_sensor` VALUES (92, 91);
INSERT INTO `Sensor` (`id`) VALUES (93);
INSERT INTO `TrackElement_sensor` VALUES (86, 93);
INSERT INTO `Route_routeDefinition` VALUES (3, 93);
INSERT INTO `TrackElement` VALUES (94);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (94, 618);
INSERT INTO `TrackElement_sensor` VALUES (94, 93);
INSERT INTO `Sensor` (`id`) VALUES (95);
INSERT INTO `TrackElement_sensor` VALUES (86, 95);
INSERT INTO `Route_routeDefinition` VALUES (3, 95);
INSERT INTO `TrackElement` VALUES (96);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (96, 180);
INSERT INTO `TrackElement_sensor` VALUES (96, 95);
INSERT INTO `Sensor` (`id`) VALUES (97);
INSERT INTO `TrackElement_sensor` VALUES (86, 97);
INSERT INTO `Route_routeDefinition` VALUES (3, 97);
INSERT INTO `TrackElement` VALUES (98);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (98, 744);
INSERT INTO `TrackElement_sensor` VALUES (98, 97);
INSERT INTO `Sensor` (`id`) VALUES (99);
INSERT INTO `TrackElement` VALUES (100);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (100, 762);
INSERT INTO `TrackElement_sensor` VALUES (100, 99);
INSERT INTO `Sensor` (`id`) VALUES (101);
INSERT INTO `TrackElement_sensor` VALUES (86, 101);
INSERT INTO `Route_routeDefinition` VALUES (3, 101);
INSERT INTO `TrackElement` VALUES (102);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (102, 735);
INSERT INTO `TrackElement_sensor` VALUES (102, 101);
INSERT INTO `Sensor` (`id`) VALUES (103);
INSERT INTO `TrackElement_sensor` VALUES (86, 103);
INSERT INTO `Route_routeDefinition` VALUES (3, 103);
INSERT INTO `TrackElement` VALUES (104);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (104, 745);
INSERT INTO `TrackElement_sensor` VALUES (104, 103);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 86;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (105, 1, 86, 3);
INSERT INTO `TrackElement` VALUES (106);
INSERT INTO `Switch` (`id`) VALUES (106);
INSERT INTO `Sensor` (`id`) VALUES (107);
INSERT INTO `TrackElement_sensor` VALUES (106, 107);
INSERT INTO `Route_routeDefinition` VALUES (3, 107);
INSERT INTO `TrackElement` VALUES (108);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (108, 101);
INSERT INTO `TrackElement_sensor` VALUES (108, 107);
INSERT INTO `Sensor` (`id`) VALUES (109);
INSERT INTO `TrackElement_sensor` VALUES (106, 109);
INSERT INTO `Route_routeDefinition` VALUES (3, 109);
INSERT INTO `TrackElement` VALUES (110);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (110, -784);
INSERT INTO `TrackElement_sensor` VALUES (110, 109);
INSERT INTO `Sensor` (`id`) VALUES (111);
INSERT INTO `TrackElement_sensor` VALUES (106, 111);
INSERT INTO `Route_routeDefinition` VALUES (3, 111);
INSERT INTO `TrackElement` VALUES (112);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (112, 385);
INSERT INTO `TrackElement_sensor` VALUES (112, 111);
INSERT INTO `Sensor` (`id`) VALUES (113);
INSERT INTO `TrackElement_sensor` VALUES (106, 113);
INSERT INTO `Route_routeDefinition` VALUES (3, 113);
INSERT INTO `TrackElement` VALUES (114);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (114, 656);
INSERT INTO `TrackElement_sensor` VALUES (114, 113);
INSERT INTO `Sensor` (`id`) VALUES (115);
INSERT INTO `TrackElement_sensor` VALUES (106, 115);
INSERT INTO `Route_routeDefinition` VALUES (3, 115);
INSERT INTO `TrackElement` VALUES (116);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (116, 118);
INSERT INTO `TrackElement_sensor` VALUES (116, 115);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 106;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (117, 1, 106, 3);
INSERT INTO `TrackElement` VALUES (118);
INSERT INTO `Switch` (`id`) VALUES (118);
INSERT INTO `Sensor` (`id`) VALUES (119);
INSERT INTO `TrackElement_sensor` VALUES (118, 119);
INSERT INTO `Route_routeDefinition` VALUES (3, 119);
INSERT INTO `TrackElement` VALUES (120);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (120, 781);
INSERT INTO `TrackElement_sensor` VALUES (120, 119);
INSERT INTO `Sensor` (`id`) VALUES (121);
INSERT INTO `TrackElement_sensor` VALUES (118, 121);
INSERT INTO `Route_routeDefinition` VALUES (3, 121);
INSERT INTO `TrackElement` VALUES (122);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (122, 906);
INSERT INTO `TrackElement_sensor` VALUES (122, 121);
INSERT INTO `Sensor` (`id`) VALUES (123);
INSERT INTO `TrackElement_sensor` VALUES (118, 123);
INSERT INTO `Route_routeDefinition` VALUES (3, 123);
INSERT INTO `TrackElement` VALUES (124);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (124, 532);
INSERT INTO `TrackElement_sensor` VALUES (124, 123);
INSERT INTO `Sensor` (`id`) VALUES (125);
INSERT INTO `TrackElement_sensor` VALUES (118, 125);
INSERT INTO `TrackElement` VALUES (126);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (126, 297);
INSERT INTO `TrackElement_sensor` VALUES (126, 125);
INSERT INTO `Sensor` (`id`) VALUES (127);
INSERT INTO `TrackElement_sensor` VALUES (118, 127);
INSERT INTO `Route_routeDefinition` VALUES (3, 127);
INSERT INTO `TrackElement` VALUES (128);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (128, 218);
INSERT INTO `TrackElement_sensor` VALUES (128, 127);
INSERT INTO `Sensor` (`id`) VALUES (129);
INSERT INTO `TrackElement_sensor` VALUES (118, 129);
INSERT INTO `Route_routeDefinition` VALUES (3, 129);
INSERT INTO `TrackElement` VALUES (130);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (130, 520);
INSERT INTO `TrackElement_sensor` VALUES (130, 129);
INSERT INTO `Sensor` (`id`) VALUES (131);
INSERT INTO `TrackElement_sensor` VALUES (118, 131);
INSERT INTO `Route_routeDefinition` VALUES (3, 131);
INSERT INTO `TrackElement` VALUES (132);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (132, 249);
INSERT INTO `TrackElement_sensor` VALUES (132, 131);
INSERT INTO `Sensor` (`id`) VALUES (133);
INSERT INTO `TrackElement_sensor` VALUES (118, 133);
INSERT INTO `Route_routeDefinition` VALUES (3, 133);
INSERT INTO `TrackElement` VALUES (134);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (134, 38);
INSERT INTO `TrackElement_sensor` VALUES (134, 133);
INSERT INTO `Sensor` (`id`) VALUES (135);
INSERT INTO `TrackElement_sensor` VALUES (118, 135);
INSERT INTO `Route_routeDefinition` VALUES (3, 135);
INSERT INTO `TrackElement` VALUES (136);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (136, 962);
INSERT INTO `TrackElement_sensor` VALUES (136, 135);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 118;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (137, 1, 118, 3);
INSERT INTO `TrackElement` VALUES (138);
INSERT INTO `Switch` (`id`) VALUES (138);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 138;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (139, 0, 138, 3);
INSERT INTO `TrackElement` VALUES (140);
INSERT INTO `Switch` (`id`) VALUES (140);
INSERT INTO `Sensor` (`id`) VALUES (141);
INSERT INTO `TrackElement_sensor` VALUES (140, 141);
INSERT INTO `Route_routeDefinition` VALUES (3, 141);
INSERT INTO `TrackElement` VALUES (142);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (142, 685);
INSERT INTO `TrackElement_sensor` VALUES (142, 141);
INSERT INTO `Sensor` (`id`) VALUES (143);
INSERT INTO `TrackElement_sensor` VALUES (140, 143);
INSERT INTO `Route_routeDefinition` VALUES (3, 143);
INSERT INTO `TrackElement` VALUES (144);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (144, 402);
INSERT INTO `TrackElement_sensor` VALUES (144, 143);
INSERT INTO `Sensor` (`id`) VALUES (145);
INSERT INTO `TrackElement_sensor` VALUES (140, 145);
INSERT INTO `Route_routeDefinition` VALUES (3, 145);
INSERT INTO `TrackElement` VALUES (146);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (146, 869);
INSERT INTO `TrackElement_sensor` VALUES (146, 145);
INSERT INTO `Sensor` (`id`) VALUES (147);
INSERT INTO `TrackElement_sensor` VALUES (140, 147);
INSERT INTO `Route_routeDefinition` VALUES (3, 147);
INSERT INTO `TrackElement` VALUES (148);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (148, 332);
INSERT INTO `TrackElement_sensor` VALUES (148, 147);
INSERT INTO `Sensor` (`id`) VALUES (149);
INSERT INTO `TrackElement_sensor` VALUES (140, 149);
INSERT INTO `Route_routeDefinition` VALUES (3, 149);
INSERT INTO `TrackElement` VALUES (150);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (150, 626);
INSERT INTO `TrackElement_sensor` VALUES (150, 149);
INSERT INTO `Sensor` (`id`) VALUES (151);
INSERT INTO `TrackElement_sensor` VALUES (140, 151);
INSERT INTO `Route_routeDefinition` VALUES (3, 151);
INSERT INTO `TrackElement` VALUES (152);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (152, 10);
INSERT INTO `TrackElement_sensor` VALUES (152, 151);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 140;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (153, 1, 140, 3);
INSERT INTO `TrackElement` VALUES (154);
INSERT INTO `Switch` (`id`) VALUES (154);
INSERT INTO `Sensor` (`id`) VALUES (155);
INSERT INTO `TrackElement_sensor` VALUES (154, 155);
INSERT INTO `Route_routeDefinition` VALUES (3, 155);
INSERT INTO `TrackElement` VALUES (156);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (156, -770);
INSERT INTO `TrackElement_sensor` VALUES (156, 155);
INSERT INTO `Sensor` (`id`) VALUES (157);
INSERT INTO `TrackElement_sensor` VALUES (154, 157);
INSERT INTO `Route_routeDefinition` VALUES (3, 157);
INSERT INTO `TrackElement` VALUES (158);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (158, 963);
INSERT INTO `TrackElement_sensor` VALUES (158, 157);
INSERT INTO `Sensor` (`id`) VALUES (159);
INSERT INTO `TrackElement_sensor` VALUES (154, 159);
INSERT INTO `Route_routeDefinition` VALUES (3, 159);
INSERT INTO `TrackElement` VALUES (160);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (160, 89);
INSERT INTO `TrackElement_sensor` VALUES (160, 159);
INSERT INTO `Sensor` (`id`) VALUES (161);
INSERT INTO `TrackElement_sensor` VALUES (154, 161);
INSERT INTO `Route_routeDefinition` VALUES (3, 161);
INSERT INTO `TrackElement` VALUES (162);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (162, 684);
INSERT INTO `TrackElement_sensor` VALUES (162, 161);
INSERT INTO `Sensor` (`id`) VALUES (163);
INSERT INTO `TrackElement_sensor` VALUES (154, 163);
INSERT INTO `TrackElement` VALUES (164);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (164, 110);
INSERT INTO `TrackElement_sensor` VALUES (164, 163);
INSERT INTO `Sensor` (`id`) VALUES (165);
INSERT INTO `TrackElement_sensor` VALUES (154, 165);
INSERT INTO `Route_routeDefinition` VALUES (3, 165);
INSERT INTO `TrackElement` VALUES (166);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (166, -35);
INSERT INTO `TrackElement_sensor` VALUES (166, 165);
INSERT INTO `Sensor` (`id`) VALUES (167);
INSERT INTO `TrackElement_sensor` VALUES (154, 167);
INSERT INTO `Route_routeDefinition` VALUES (3, 167);
INSERT INTO `TrackElement` VALUES (168);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (168, 917);
INSERT INTO `TrackElement_sensor` VALUES (168, 167);
INSERT INTO `Sensor` (`id`) VALUES (169);
INSERT INTO `TrackElement_sensor` VALUES (154, 169);
INSERT INTO `Route_routeDefinition` VALUES (3, 169);
INSERT INTO `TrackElement` VALUES (170);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (170, 819);
INSERT INTO `TrackElement_sensor` VALUES (170, 169);
INSERT INTO `Sensor` (`id`) VALUES (171);
INSERT INTO `TrackElement_sensor` VALUES (154, 171);
INSERT INTO `Route_routeDefinition` VALUES (3, 171);
INSERT INTO `TrackElement` VALUES (172);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (172, 713);
INSERT INTO `TrackElement_sensor` VALUES (172, 171);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 154;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (173, 0, 154, 3);
INSERT INTO `TrackElement` VALUES (174);
INSERT INTO `Switch` (`id`) VALUES (174);
INSERT INTO `Sensor` (`id`) VALUES (175);
INSERT INTO `TrackElement_sensor` VALUES (174, 175);
INSERT INTO `Route_routeDefinition` VALUES (3, 175);
INSERT INTO `TrackElement` VALUES (176);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (176, 368);
INSERT INTO `TrackElement_sensor` VALUES (176, 175);
INSERT INTO `Sensor` (`id`) VALUES (177);
INSERT INTO `TrackElement_sensor` VALUES (174, 177);
INSERT INTO `Route_routeDefinition` VALUES (3, 177);
INSERT INTO `TrackElement` VALUES (178);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (178, -736);
INSERT INTO `TrackElement_sensor` VALUES (178, 177);
INSERT INTO `Sensor` (`id`) VALUES (179);
INSERT INTO `TrackElement_sensor` VALUES (174, 179);
INSERT INTO `Route_routeDefinition` VALUES (3, 179);
INSERT INTO `TrackElement` VALUES (180);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (180, 148);
INSERT INTO `TrackElement_sensor` VALUES (180, 179);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 174;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (181, 1, 174, 3);
INSERT INTO `TrackElement` VALUES (182);
INSERT INTO `Switch` (`id`) VALUES (182);
INSERT INTO `Sensor` (`id`) VALUES (183);
INSERT INTO `TrackElement_sensor` VALUES (182, 183);
INSERT INTO `Route_routeDefinition` VALUES (3, 183);
INSERT INTO `TrackElement` VALUES (184);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (184, 808);
INSERT INTO `TrackElement_sensor` VALUES (184, 183);
INSERT INTO `Sensor` (`id`) VALUES (185);
INSERT INTO `TrackElement_sensor` VALUES (182, 185);
INSERT INTO `Route_routeDefinition` VALUES (3, 185);
INSERT INTO `TrackElement` VALUES (186);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (186, 743);
INSERT INTO `TrackElement_sensor` VALUES (186, 185);
INSERT INTO `Sensor` (`id`) VALUES (187);
INSERT INTO `TrackElement_sensor` VALUES (182, 187);
INSERT INTO `Route_routeDefinition` VALUES (3, 187);
INSERT INTO `TrackElement` VALUES (188);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (188, 223);
INSERT INTO `TrackElement_sensor` VALUES (188, 187);
INSERT INTO `Sensor` (`id`) VALUES (189);
INSERT INTO `TrackElement_sensor` VALUES (182, 189);
INSERT INTO `Route_routeDefinition` VALUES (3, 189);
INSERT INTO `TrackElement` VALUES (190);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (190, 932);
INSERT INTO `TrackElement_sensor` VALUES (190, 189);
INSERT INTO `Sensor` (`id`) VALUES (191);
INSERT INTO `TrackElement_sensor` VALUES (182, 191);
INSERT INTO `Route_routeDefinition` VALUES (3, 191);
INSERT INTO `TrackElement` VALUES (192);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (192, 643);
INSERT INTO `TrackElement_sensor` VALUES (192, 191);
INSERT INTO `Sensor` (`id`) VALUES (193);
INSERT INTO `TrackElement_sensor` VALUES (182, 193);
INSERT INTO `Route_routeDefinition` VALUES (3, 193);
INSERT INTO `TrackElement` VALUES (194);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (194, 642);
INSERT INTO `TrackElement_sensor` VALUES (194, 193);
INSERT INTO `Sensor` (`id`) VALUES (195);
INSERT INTO `TrackElement_sensor` VALUES (182, 195);
INSERT INTO `TrackElement` VALUES (196);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (196, 156);
INSERT INTO `TrackElement_sensor` VALUES (196, 195);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 182;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (197, 2, 182, 3);
INSERT INTO `TrackElement` VALUES (198);
INSERT INTO `Switch` (`id`) VALUES (198);
INSERT INTO `Sensor` (`id`) VALUES (199);
INSERT INTO `TrackElement_sensor` VALUES (198, 199);
INSERT INTO `Route_routeDefinition` VALUES (3, 199);
INSERT INTO `TrackElement` VALUES (200);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (200, 535);
INSERT INTO `TrackElement_sensor` VALUES (200, 199);
INSERT INTO `Sensor` (`id`) VALUES (201);
INSERT INTO `TrackElement_sensor` VALUES (198, 201);
INSERT INTO `Route_routeDefinition` VALUES (3, 201);
INSERT INTO `TrackElement` VALUES (202);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (202, 282);
INSERT INTO `TrackElement_sensor` VALUES (202, 201);
INSERT INTO `Sensor` (`id`) VALUES (203);
INSERT INTO `TrackElement_sensor` VALUES (198, 203);
INSERT INTO `Route_routeDefinition` VALUES (3, 203);
INSERT INTO `TrackElement` VALUES (204);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (204, 463);
INSERT INTO `TrackElement_sensor` VALUES (204, 203);
INSERT INTO `Sensor` (`id`) VALUES (205);
INSERT INTO `TrackElement_sensor` VALUES (198, 205);
INSERT INTO `Route_routeDefinition` VALUES (3, 205);
INSERT INTO `TrackElement` VALUES (206);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (206, 149);
INSERT INTO `TrackElement_sensor` VALUES (206, 205);
INSERT INTO `Sensor` (`id`) VALUES (207);
INSERT INTO `TrackElement_sensor` VALUES (198, 207);
INSERT INTO `Route_routeDefinition` VALUES (3, 207);
INSERT INTO `TrackElement` VALUES (208);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (208, 682);
INSERT INTO `TrackElement_sensor` VALUES (208, 207);
INSERT INTO `Sensor` (`id`) VALUES (209);
INSERT INTO `TrackElement_sensor` VALUES (198, 209);
INSERT INTO `TrackElement` VALUES (210);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (210, 776);
INSERT INTO `TrackElement_sensor` VALUES (210, 209);
INSERT INTO `Sensor` (`id`) VALUES (211);
INSERT INTO `TrackElement` VALUES (212);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (212, 370);
INSERT INTO `TrackElement_sensor` VALUES (212, 211);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 198;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (213, 1, 198, 3);
INSERT INTO `TrackElement` VALUES (214);
INSERT INTO `Switch` (`id`) VALUES (214);
INSERT INTO `Sensor` (`id`) VALUES (215);
INSERT INTO `TrackElement_sensor` VALUES (214, 215);
INSERT INTO `Route_routeDefinition` VALUES (3, 215);
INSERT INTO `TrackElement` VALUES (216);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (216, 575);
INSERT INTO `TrackElement_sensor` VALUES (216, 215);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 214;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (217, 3, 214, 3);
INSERT INTO `TrackElement` VALUES (218);
INSERT INTO `Switch` (`id`) VALUES (218);
INSERT INTO `Sensor` (`id`) VALUES (219);
INSERT INTO `TrackElement_sensor` VALUES (218, 219);
INSERT INTO `Route_routeDefinition` VALUES (3, 219);
INSERT INTO `TrackElement` VALUES (220);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (220, 82);
INSERT INTO `TrackElement_sensor` VALUES (220, 219);
INSERT INTO `Sensor` (`id`) VALUES (221);
INSERT INTO `TrackElement_sensor` VALUES (218, 221);
INSERT INTO `Route_routeDefinition` VALUES (3, 221);
INSERT INTO `TrackElement` VALUES (222);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (222, 917);
INSERT INTO `TrackElement_sensor` VALUES (222, 221);
INSERT INTO `Sensor` (`id`) VALUES (223);
INSERT INTO `TrackElement_sensor` VALUES (218, 223);
INSERT INTO `Route_routeDefinition` VALUES (3, 223);
INSERT INTO `TrackElement` VALUES (224);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (224, 849);
INSERT INTO `TrackElement_sensor` VALUES (224, 223);
INSERT INTO `Sensor` (`id`) VALUES (225);
INSERT INTO `TrackElement` VALUES (226);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (226, 846);
INSERT INTO `TrackElement_sensor` VALUES (226, 225);
INSERT INTO `Sensor` (`id`) VALUES (227);
INSERT INTO `TrackElement_sensor` VALUES (218, 227);
INSERT INTO `Route_routeDefinition` VALUES (3, 227);
INSERT INTO `TrackElement` VALUES (228);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (228, 976);
INSERT INTO `TrackElement_sensor` VALUES (228, 227);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 218;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (229, 2, 218, 3);
INSERT INTO `TrackElement_connectsTo` VALUES (4, 6);
INSERT INTO `TrackElement_connectsTo` VALUES (6, 8);
INSERT INTO `TrackElement_connectsTo` VALUES (8, 10);
INSERT INTO `TrackElement_connectsTo` VALUES (10, 12);
INSERT INTO `TrackElement_connectsTo` VALUES (12, 14);
INSERT INTO `TrackElement_connectsTo` VALUES (14, 16);
INSERT INTO `TrackElement_connectsTo` VALUES (16, 18);
INSERT INTO `TrackElement_connectsTo` VALUES (18, 20);
INSERT INTO `TrackElement_connectsTo` VALUES (20, 22);
INSERT INTO `TrackElement_connectsTo` VALUES (22, 24);
INSERT INTO `TrackElement_connectsTo` VALUES (24, 26);
INSERT INTO `TrackElement_connectsTo` VALUES (26, 28);
INSERT INTO `TrackElement_connectsTo` VALUES (28, 30);
INSERT INTO `TrackElement_connectsTo` VALUES (30, 32);
INSERT INTO `TrackElement_connectsTo` VALUES (32, 34);
INSERT INTO `TrackElement_connectsTo` VALUES (34, 36);
INSERT INTO `TrackElement_connectsTo` VALUES (36, 38);
INSERT INTO `TrackElement_connectsTo` VALUES (38, 40);
INSERT INTO `TrackElement_connectsTo` VALUES (40, 42);
INSERT INTO `TrackElement_connectsTo` VALUES (42, 44);
INSERT INTO `TrackElement_connectsTo` VALUES (44, 46);
INSERT INTO `TrackElement_connectsTo` VALUES (46, 48);
INSERT INTO `TrackElement_connectsTo` VALUES (48, 50);
INSERT INTO `TrackElement_connectsTo` VALUES (50, 52);
INSERT INTO `TrackElement_connectsTo` VALUES (52, 54);
INSERT INTO `TrackElement_connectsTo` VALUES (54, 56);
INSERT INTO `TrackElement_connectsTo` VALUES (56, 58);
INSERT INTO `TrackElement_connectsTo` VALUES (58, 60);
INSERT INTO `TrackElement_connectsTo` VALUES (60, 62);
INSERT INTO `TrackElement_connectsTo` VALUES (62, 64);
INSERT INTO `TrackElement_connectsTo` VALUES (64, 66);
INSERT INTO `TrackElement_connectsTo` VALUES (66, 68);
INSERT INTO `TrackElement_connectsTo` VALUES (68, 70);
INSERT INTO `TrackElement_connectsTo` VALUES (70, 72);
INSERT INTO `TrackElement_connectsTo` VALUES (72, 74);
INSERT INTO `TrackElement_connectsTo` VALUES (74, 76);
INSERT INTO `TrackElement_connectsTo` VALUES (76, 78);
INSERT INTO `TrackElement_connectsTo` VALUES (78, 80);
INSERT INTO `TrackElement_connectsTo` VALUES (80, 82);
INSERT INTO `TrackElement_connectsTo` VALUES (82, 84);
INSERT INTO `TrackElement_connectsTo` VALUES (84, 86);
INSERT INTO `TrackElement_connectsTo` VALUES (86, 88);
INSERT INTO `TrackElement_connectsTo` VALUES (88, 90);
INSERT INTO `TrackElement_connectsTo` VALUES (90, 92);
INSERT INTO `TrackElement_connectsTo` VALUES (92, 94);
INSERT INTO `TrackElement_connectsTo` VALUES (94, 96);
INSERT INTO `TrackElement_connectsTo` VALUES (96, 98);
INSERT INTO `TrackElement_connectsTo` VALUES (98, 100);
INSERT INTO `TrackElement_connectsTo` VALUES (100, 102);
INSERT INTO `TrackElement_connectsTo` VALUES (102, 104);
INSERT INTO `TrackElement_connectsTo` VALUES (104, 106);
INSERT INTO `TrackElement_connectsTo` VALUES (106, 108);
INSERT INTO `TrackElement_connectsTo` VALUES (108, 110);
INSERT INTO `TrackElement_connectsTo` VALUES (110, 112);
INSERT INTO `TrackElement_connectsTo` VALUES (112, 114);
INSERT INTO `TrackElement_connectsTo` VALUES (114, 116);
INSERT INTO `TrackElement_connectsTo` VALUES (116, 118);
INSERT INTO `TrackElement_connectsTo` VALUES (118, 120);
INSERT INTO `TrackElement_connectsTo` VALUES (120, 122);
INSERT INTO `TrackElement_connectsTo` VALUES (122, 124);
INSERT INTO `TrackElement_connectsTo` VALUES (124, 126);
INSERT INTO `TrackElement_connectsTo` VALUES (126, 128);
INSERT INTO `TrackElement_connectsTo` VALUES (128, 130);
INSERT INTO `TrackElement_connectsTo` VALUES (130, 132);
INSERT INTO `TrackElement_connectsTo` VALUES (132, 134);
INSERT INTO `TrackElement_connectsTo` VALUES (134, 136);
INSERT INTO `TrackElement_connectsTo` VALUES (136, 138);
INSERT INTO `TrackElement_connectsTo` VALUES (138, 140);
INSERT INTO `TrackElement_connectsTo` VALUES (140, 142);
INSERT INTO `TrackElement_connectsTo` VALUES (142, 144);
INSERT INTO `TrackElement_connectsTo` VALUES (144, 146);
INSERT INTO `TrackElement_connectsTo` VALUES (146, 148);
INSERT INTO `TrackElement_connectsTo` VALUES (148, 150);
INSERT INTO `TrackElement_connectsTo` VALUES (150, 152);
INSERT INTO `TrackElement_connectsTo` VALUES (152, 154);
INSERT INTO `TrackElement_connectsTo` VALUES (154, 156);
INSERT INTO `TrackElement_connectsTo` VALUES (156, 158);
INSERT INTO `TrackElement_connectsTo` VALUES (158, 160);
INSERT INTO `TrackElement_connectsTo` VALUES (160, 162);
INSERT INTO `TrackElement_connectsTo` VALUES (162, 164);
INSERT INTO `TrackElement_connectsTo` VALUES (164, 166);
INSERT INTO `TrackElement_connectsTo` VALUES (166, 168);
INSERT INTO `TrackElement_connectsTo` VALUES (168, 170);
INSERT INTO `TrackElement_connectsTo` VALUES (170, 172);
INSERT INTO `TrackElement_connectsTo` VALUES (172, 174);
INSERT INTO `TrackElement_connectsTo` VALUES (174, 176);
INSERT INTO `TrackElement_connectsTo` VALUES (176, 178);
INSERT INTO `TrackElement_connectsTo` VALUES (178, 180);
INSERT INTO `TrackElement_connectsTo` VALUES (180, 182);
INSERT INTO `TrackElement_connectsTo` VALUES (182, 184);
INSERT INTO `TrackElement_connectsTo` VALUES (184, 186);
INSERT INTO `TrackElement_connectsTo` VALUES (186, 188);
INSERT INTO `TrackElement_connectsTo` VALUES (188, 190);
INSERT INTO `TrackElement_connectsTo` VALUES (190, 192);
INSERT INTO `TrackElement_connectsTo` VALUES (192, 194);
INSERT INTO `TrackElement_connectsTo` VALUES (194, 196);
INSERT INTO `TrackElement_connectsTo` VALUES (196, 198);
INSERT INTO `TrackElement_connectsTo` VALUES (198, 200);
INSERT INTO `TrackElement_connectsTo` VALUES (200, 202);
INSERT INTO `TrackElement_connectsTo` VALUES (202, 204);
INSERT INTO `TrackElement_connectsTo` VALUES (204, 206);
INSERT INTO `TrackElement_connectsTo` VALUES (206, 208);
INSERT INTO `TrackElement_connectsTo` VALUES (208, 210);
INSERT INTO `TrackElement_connectsTo` VALUES (210, 212);
INSERT INTO `TrackElement_connectsTo` VALUES (212, 214);
INSERT INTO `TrackElement_connectsTo` VALUES (214, 216);
INSERT INTO `TrackElement_connectsTo` VALUES (216, 218);
INSERT INTO `TrackElement_connectsTo` VALUES (218, 220);
INSERT INTO `TrackElement_connectsTo` VALUES (220, 222);
INSERT INTO `TrackElement_connectsTo` VALUES (222, 224);
INSERT INTO `TrackElement_connectsTo` VALUES (224, 226);
INSERT INTO `TrackElement_connectsTo` VALUES (226, 228);
INSERT INTO `Route` (`id`, `Route_entry`, `Route_exit`) VALUES (230, 2, 1);
INSERT INTO `TrackElement` VALUES (231);
INSERT INTO `Switch` (`id`) VALUES (231);
INSERT INTO `Sensor` (`id`) VALUES (232);
INSERT INTO `TrackElement_sensor` VALUES (231, 232);
INSERT INTO `Route_routeDefinition` VALUES (230, 232);
INSERT INTO `TrackElement` VALUES (233);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (233, 20);
INSERT INTO `TrackElement_sensor` VALUES (233, 232);
INSERT INTO `Sensor` (`id`) VALUES (234);
INSERT INTO `TrackElement_sensor` VALUES (231, 234);
INSERT INTO `Route_routeDefinition` VALUES (230, 234);
INSERT INTO `TrackElement` VALUES (235);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (235, 290);
INSERT INTO `TrackElement_sensor` VALUES (235, 234);
INSERT INTO `Sensor` (`id`) VALUES (236);
INSERT INTO `TrackElement_sensor` VALUES (231, 236);
INSERT INTO `Route_routeDefinition` VALUES (230, 236);
INSERT INTO `TrackElement` VALUES (237);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (237, 521);
INSERT INTO `TrackElement_sensor` VALUES (237, 236);
INSERT INTO `Sensor` (`id`) VALUES (238);
INSERT INTO `TrackElement_sensor` VALUES (231, 238);
INSERT INTO `Route_routeDefinition` VALUES (230, 238);
INSERT INTO `TrackElement` VALUES (239);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (239, 459);
INSERT INTO `TrackElement_sensor` VALUES (239, 238);
INSERT INTO `Sensor` (`id`) VALUES (240);
INSERT INTO `TrackElement_sensor` VALUES (231, 240);
INSERT INTO `Route_routeDefinition` VALUES (230, 240);
INSERT INTO `TrackElement` VALUES (241);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (241, 821);
INSERT INTO `TrackElement_sensor` VALUES (241, 240);
INSERT INTO `Sensor` (`id`) VALUES (242);
INSERT INTO `TrackElement_sensor` VALUES (231, 242);
INSERT INTO `Route_routeDefinition` VALUES (230, 242);
INSERT INTO `TrackElement` VALUES (243);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (243, 826);
INSERT INTO `TrackElement_sensor` VALUES (243, 242);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 231;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (244, 0, 231, 230);
INSERT INTO `TrackElement` VALUES (245);
INSERT INTO `Switch` (`id`) VALUES (245);
INSERT INTO `Sensor` (`id`) VALUES (246);
INSERT INTO `TrackElement_sensor` VALUES (245, 246);
INSERT INTO `Route_routeDefinition` VALUES (230, 246);
INSERT INTO `TrackElement` VALUES (247);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (247, -592);
INSERT INTO `TrackElement_sensor` VALUES (247, 246);
INSERT INTO `Sensor` (`id`) VALUES (248);
INSERT INTO `TrackElement_sensor` VALUES (245, 248);
INSERT INTO `Route_routeDefinition` VALUES (230, 248);
INSERT INTO `TrackElement` VALUES (249);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (249, 672);
INSERT INTO `TrackElement_sensor` VALUES (249, 248);
INSERT INTO `Sensor` (`id`) VALUES (250);
INSERT INTO `TrackElement_sensor` VALUES (245, 250);
INSERT INTO `Route_routeDefinition` VALUES (230, 250);
INSERT INTO `TrackElement` VALUES (251);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (251, 420);
INSERT INTO `TrackElement_sensor` VALUES (251, 250);
INSERT INTO `Sensor` (`id`) VALUES (252);
INSERT INTO `TrackElement_sensor` VALUES (245, 252);
INSERT INTO `Route_routeDefinition` VALUES (230, 252);
INSERT INTO `TrackElement` VALUES (253);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (253, 529);
INSERT INTO `TrackElement_sensor` VALUES (253, 252);
INSERT INTO `Sensor` (`id`) VALUES (254);
INSERT INTO `TrackElement_sensor` VALUES (245, 254);
INSERT INTO `Route_routeDefinition` VALUES (230, 254);
INSERT INTO `TrackElement` VALUES (255);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (255, 857);
INSERT INTO `TrackElement_sensor` VALUES (255, 254);
INSERT INTO `Sensor` (`id`) VALUES (256);
INSERT INTO `TrackElement_sensor` VALUES (245, 256);
INSERT INTO `TrackElement` VALUES (257);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (257, 749);
INSERT INTO `TrackElement_sensor` VALUES (257, 256);
INSERT INTO `Sensor` (`id`) VALUES (258);
INSERT INTO `TrackElement_sensor` VALUES (245, 258);
INSERT INTO `Route_routeDefinition` VALUES (230, 258);
INSERT INTO `TrackElement` VALUES (259);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (259, 78);
INSERT INTO `TrackElement_sensor` VALUES (259, 258);
INSERT INTO `Sensor` (`id`) VALUES (260);
INSERT INTO `TrackElement_sensor` VALUES (245, 260);
INSERT INTO `Route_routeDefinition` VALUES (230, 260);
INSERT INTO `TrackElement` VALUES (261);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (261, 492);
INSERT INTO `TrackElement_sensor` VALUES (261, 260);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 245;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (262, 2, 245, 230);
INSERT INTO `TrackElement` VALUES (263);
INSERT INTO `Switch` (`id`) VALUES (263);
INSERT INTO `Sensor` (`id`) VALUES (264);
INSERT INTO `TrackElement_sensor` VALUES (263, 264);
INSERT INTO `Route_routeDefinition` VALUES (230, 264);
INSERT INTO `TrackElement` VALUES (265);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (265, 88);
INSERT INTO `TrackElement_sensor` VALUES (265, 264);
INSERT INTO `Sensor` (`id`) VALUES (266);
INSERT INTO `TrackElement_sensor` VALUES (263, 266);
INSERT INTO `Route_routeDefinition` VALUES (230, 266);
INSERT INTO `TrackElement` VALUES (267);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (267, 734);
INSERT INTO `TrackElement_sensor` VALUES (267, 266);
INSERT INTO `Sensor` (`id`) VALUES (268);
INSERT INTO `TrackElement_sensor` VALUES (263, 268);
INSERT INTO `Route_routeDefinition` VALUES (230, 268);
INSERT INTO `TrackElement` VALUES (269);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (269, 28);
INSERT INTO `TrackElement_sensor` VALUES (269, 268);
INSERT INTO `Sensor` (`id`) VALUES (270);
INSERT INTO `TrackElement_sensor` VALUES (263, 270);
INSERT INTO `Route_routeDefinition` VALUES (230, 270);
INSERT INTO `TrackElement` VALUES (271);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (271, 224);
INSERT INTO `TrackElement_sensor` VALUES (271, 270);
INSERT INTO `Sensor` (`id`) VALUES (272);
INSERT INTO `TrackElement_sensor` VALUES (263, 272);
INSERT INTO `Route_routeDefinition` VALUES (230, 272);
INSERT INTO `TrackElement` VALUES (273);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (273, 516);
INSERT INTO `TrackElement_sensor` VALUES (273, 272);
INSERT INTO `Sensor` (`id`) VALUES (274);
INSERT INTO `TrackElement_sensor` VALUES (263, 274);
INSERT INTO `Route_routeDefinition` VALUES (230, 274);
INSERT INTO `TrackElement` VALUES (275);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (275, -466);
INSERT INTO `TrackElement_sensor` VALUES (275, 274);
INSERT INTO `Sensor` (`id`) VALUES (276);
INSERT INTO `TrackElement_sensor` VALUES (263, 276);
INSERT INTO `Route_routeDefinition` VALUES (230, 276);
INSERT INTO `TrackElement` VALUES (277);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (277, 521);
INSERT INTO `TrackElement_sensor` VALUES (277, 276);
INSERT INTO `Sensor` (`id`) VALUES (278);
INSERT INTO `TrackElement_sensor` VALUES (263, 278);
INSERT INTO `Route_routeDefinition` VALUES (230, 278);
INSERT INTO `TrackElement` VALUES (279);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (279, 939);
INSERT INTO `TrackElement_sensor` VALUES (279, 278);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 263;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (280, 1, 263, 230);
INSERT INTO `TrackElement` VALUES (281);
INSERT INTO `Switch` (`id`) VALUES (281);
INSERT INTO `Sensor` (`id`) VALUES (282);
INSERT INTO `TrackElement_sensor` VALUES (281, 282);
INSERT INTO `Route_routeDefinition` VALUES (230, 282);
INSERT INTO `TrackElement` VALUES (283);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (283, 162);
INSERT INTO `TrackElement_sensor` VALUES (283, 282);
INSERT INTO `Sensor` (`id`) VALUES (284);
INSERT INTO `TrackElement_sensor` VALUES (281, 284);
INSERT INTO `Route_routeDefinition` VALUES (230, 284);
INSERT INTO `TrackElement` VALUES (285);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (285, 509);
INSERT INTO `TrackElement_sensor` VALUES (285, 284);
INSERT INTO `Sensor` (`id`) VALUES (286);
INSERT INTO `TrackElement_sensor` VALUES (281, 286);
INSERT INTO `Route_routeDefinition` VALUES (230, 286);
INSERT INTO `TrackElement` VALUES (287);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (287, 776);
INSERT INTO `TrackElement_sensor` VALUES (287, 286);
INSERT INTO `Sensor` (`id`) VALUES (288);
INSERT INTO `TrackElement_sensor` VALUES (281, 288);
INSERT INTO `Route_routeDefinition` VALUES (230, 288);
INSERT INTO `TrackElement` VALUES (289);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (289, 595);
INSERT INTO `TrackElement_sensor` VALUES (289, 288);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 281;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (290, 1, 281, 230);
INSERT INTO `TrackElement` VALUES (291);
INSERT INTO `Switch` (`id`) VALUES (291);
INSERT INTO `Sensor` (`id`) VALUES (292);
INSERT INTO `TrackElement_sensor` VALUES (291, 292);
INSERT INTO `Route_routeDefinition` VALUES (230, 292);
INSERT INTO `TrackElement` VALUES (293);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (293, 49);
INSERT INTO `TrackElement_sensor` VALUES (293, 292);
INSERT INTO `Sensor` (`id`) VALUES (294);
INSERT INTO `TrackElement_sensor` VALUES (291, 294);
INSERT INTO `Route_routeDefinition` VALUES (230, 294);
INSERT INTO `TrackElement` VALUES (295);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (295, 595);
INSERT INTO `TrackElement_sensor` VALUES (295, 294);
INSERT INTO `Sensor` (`id`) VALUES (296);
INSERT INTO `TrackElement_sensor` VALUES (291, 296);
INSERT INTO `Route_routeDefinition` VALUES (230, 296);
INSERT INTO `TrackElement` VALUES (297);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (297, 119);
INSERT INTO `TrackElement_sensor` VALUES (297, 296);
INSERT INTO `Sensor` (`id`) VALUES (298);
INSERT INTO `TrackElement_sensor` VALUES (291, 298);
INSERT INTO `Route_routeDefinition` VALUES (230, 298);
INSERT INTO `TrackElement` VALUES (299);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (299, 637);
INSERT INTO `TrackElement_sensor` VALUES (299, 298);
INSERT INTO `Sensor` (`id`) VALUES (300);
INSERT INTO `TrackElement_sensor` VALUES (291, 300);
INSERT INTO `Route_routeDefinition` VALUES (230, 300);
INSERT INTO `TrackElement` VALUES (301);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (301, 64);
INSERT INTO `TrackElement_sensor` VALUES (301, 300);
INSERT INTO `Sensor` (`id`) VALUES (302);
INSERT INTO `TrackElement_sensor` VALUES (291, 302);
INSERT INTO `TrackElement` VALUES (303);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (303, 390);
INSERT INTO `TrackElement_sensor` VALUES (303, 302);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 291;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (304, 1, 291, 230);
INSERT INTO `TrackElement` VALUES (305);
INSERT INTO `Switch` (`id`) VALUES (305);
INSERT INTO `Sensor` (`id`) VALUES (306);
INSERT INTO `TrackElement_sensor` VALUES (305, 306);
INSERT INTO `Route_routeDefinition` VALUES (230, 306);
INSERT INTO `TrackElement` VALUES (307);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (307, -553);
INSERT INTO `TrackElement_sensor` VALUES (307, 306);
INSERT INTO `Sensor` (`id`) VALUES (308);
INSERT INTO `TrackElement_sensor` VALUES (305, 308);
INSERT INTO `Route_routeDefinition` VALUES (230, 308);
INSERT INTO `TrackElement` VALUES (309);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (309, 805);
INSERT INTO `TrackElement_sensor` VALUES (309, 308);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 305;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (310, 1, 305, 230);
INSERT INTO `TrackElement` VALUES (311);
INSERT INTO `Switch` (`id`) VALUES (311);
INSERT INTO `Sensor` (`id`) VALUES (312);
INSERT INTO `TrackElement_sensor` VALUES (311, 312);
INSERT INTO `Route_routeDefinition` VALUES (230, 312);
INSERT INTO `TrackElement` VALUES (313);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (313, 729);
INSERT INTO `TrackElement_sensor` VALUES (313, 312);
INSERT INTO `Sensor` (`id`) VALUES (314);
INSERT INTO `TrackElement_sensor` VALUES (311, 314);
INSERT INTO `Route_routeDefinition` VALUES (230, 314);
INSERT INTO `TrackElement` VALUES (315);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (315, 58);
INSERT INTO `TrackElement_sensor` VALUES (315, 314);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 311;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (316, 0, 311, 230);
INSERT INTO `TrackElement` VALUES (317);
INSERT INTO `Switch` (`id`) VALUES (317);
INSERT INTO `Sensor` (`id`) VALUES (318);
INSERT INTO `TrackElement_sensor` VALUES (317, 318);
INSERT INTO `Route_routeDefinition` VALUES (230, 318);
INSERT INTO `TrackElement` VALUES (319);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (319, 192);
INSERT INTO `TrackElement_sensor` VALUES (319, 318);
INSERT INTO `Sensor` (`id`) VALUES (320);
INSERT INTO `TrackElement` VALUES (321);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (321, 837);
INSERT INTO `TrackElement_sensor` VALUES (321, 320);
INSERT INTO `Sensor` (`id`) VALUES (322);
INSERT INTO `TrackElement_sensor` VALUES (317, 322);
INSERT INTO `Route_routeDefinition` VALUES (230, 322);
INSERT INTO `TrackElement` VALUES (323);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (323, 844);
INSERT INTO `TrackElement_sensor` VALUES (323, 322);
INSERT INTO `Sensor` (`id`) VALUES (324);
INSERT INTO `TrackElement_sensor` VALUES (317, 324);
INSERT INTO `Route_routeDefinition` VALUES (230, 324);
INSERT INTO `TrackElement` VALUES (325);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (325, 474);
INSERT INTO `TrackElement_sensor` VALUES (325, 324);
INSERT INTO `Sensor` (`id`) VALUES (326);
INSERT INTO `TrackElement_sensor` VALUES (317, 326);
INSERT INTO `Route_routeDefinition` VALUES (230, 326);
INSERT INTO `TrackElement` VALUES (327);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (327, 356);
INSERT INTO `TrackElement_sensor` VALUES (327, 326);
INSERT INTO `Sensor` (`id`) VALUES (328);
INSERT INTO `TrackElement_sensor` VALUES (317, 328);
INSERT INTO `Route_routeDefinition` VALUES (230, 328);
INSERT INTO `TrackElement` VALUES (329);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (329, 454);
INSERT INTO `TrackElement_sensor` VALUES (329, 328);
INSERT INTO `Sensor` (`id`) VALUES (330);
INSERT INTO `TrackElement_sensor` VALUES (317, 330);
INSERT INTO `Route_routeDefinition` VALUES (230, 330);
INSERT INTO `TrackElement` VALUES (331);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (331, 181);
INSERT INTO `TrackElement_sensor` VALUES (331, 330);
INSERT INTO `Sensor` (`id`) VALUES (332);
INSERT INTO `TrackElement_sensor` VALUES (317, 332);
INSERT INTO `Route_routeDefinition` VALUES (230, 332);
INSERT INTO `TrackElement` VALUES (333);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (333, 74);
INSERT INTO `TrackElement_sensor` VALUES (333, 332);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 317;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (334, 1, 317, 230);
INSERT INTO `TrackElement` VALUES (335);
INSERT INTO `Switch` (`id`) VALUES (335);
INSERT INTO `Sensor` (`id`) VALUES (336);
INSERT INTO `TrackElement_sensor` VALUES (335, 336);
INSERT INTO `TrackElement` VALUES (337);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (337, 341);
INSERT INTO `TrackElement_sensor` VALUES (337, 336);
INSERT INTO `Sensor` (`id`) VALUES (338);
INSERT INTO `TrackElement_sensor` VALUES (335, 338);
INSERT INTO `TrackElement` VALUES (339);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (339, 952);
INSERT INTO `TrackElement_sensor` VALUES (339, 338);
INSERT INTO `Sensor` (`id`) VALUES (340);
INSERT INTO `TrackElement_sensor` VALUES (335, 340);
INSERT INTO `Route_routeDefinition` VALUES (230, 340);
INSERT INTO `TrackElement` VALUES (341);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (341, 826);
INSERT INTO `TrackElement_sensor` VALUES (341, 340);
INSERT INTO `Sensor` (`id`) VALUES (342);
INSERT INTO `TrackElement_sensor` VALUES (335, 342);
INSERT INTO `Route_routeDefinition` VALUES (230, 342);
INSERT INTO `TrackElement` VALUES (343);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (343, 497);
INSERT INTO `TrackElement_sensor` VALUES (343, 342);
INSERT INTO `Sensor` (`id`) VALUES (344);
INSERT INTO `TrackElement_sensor` VALUES (335, 344);
INSERT INTO `Route_routeDefinition` VALUES (230, 344);
INSERT INTO `TrackElement` VALUES (345);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (345, 28);
INSERT INTO `TrackElement_sensor` VALUES (345, 344);
INSERT INTO `Sensor` (`id`) VALUES (346);
INSERT INTO `TrackElement_sensor` VALUES (335, 346);
INSERT INTO `Route_routeDefinition` VALUES (230, 346);
INSERT INTO `TrackElement` VALUES (347);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (347, 62);
INSERT INTO `TrackElement_sensor` VALUES (347, 346);
INSERT INTO `Sensor` (`id`) VALUES (348);
INSERT INTO `TrackElement_sensor` VALUES (335, 348);
INSERT INTO `Route_routeDefinition` VALUES (230, 348);
INSERT INTO `TrackElement` VALUES (349);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (349, 826);
INSERT INTO `TrackElement_sensor` VALUES (349, 348);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 335;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (350, 3, 335, 230);
INSERT INTO `TrackElement` VALUES (351);
INSERT INTO `Switch` (`id`) VALUES (351);
INSERT INTO `Sensor` (`id`) VALUES (352);
INSERT INTO `TrackElement_sensor` VALUES (351, 352);
INSERT INTO `Route_routeDefinition` VALUES (230, 352);
INSERT INTO `TrackElement` VALUES (353);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (353, 883);
INSERT INTO `TrackElement_sensor` VALUES (353, 352);
INSERT INTO `Sensor` (`id`) VALUES (354);
INSERT INTO `TrackElement` VALUES (355);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (355, 624);
INSERT INTO `TrackElement_sensor` VALUES (355, 354);
INSERT INTO `Sensor` (`id`) VALUES (356);
INSERT INTO `TrackElement_sensor` VALUES (351, 356);
INSERT INTO `Route_routeDefinition` VALUES (230, 356);
INSERT INTO `TrackElement` VALUES (357);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (357, 690);
INSERT INTO `TrackElement_sensor` VALUES (357, 356);
INSERT INTO `Sensor` (`id`) VALUES (358);
INSERT INTO `TrackElement_sensor` VALUES (351, 358);
INSERT INTO `Route_routeDefinition` VALUES (230, 358);
INSERT INTO `TrackElement` VALUES (359);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (359, 658);
INSERT INTO `TrackElement_sensor` VALUES (359, 358);
INSERT INTO `Sensor` (`id`) VALUES (360);
INSERT INTO `TrackElement_sensor` VALUES (351, 360);
INSERT INTO `Route_routeDefinition` VALUES (230, 360);
INSERT INTO `TrackElement` VALUES (361);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (361, 363);
INSERT INTO `TrackElement_sensor` VALUES (361, 360);
INSERT INTO `Sensor` (`id`) VALUES (362);
INSERT INTO `TrackElement_sensor` VALUES (351, 362);
INSERT INTO `TrackElement` VALUES (363);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (363, 282);
INSERT INTO `TrackElement_sensor` VALUES (363, 362);
INSERT INTO `Sensor` (`id`) VALUES (364);
INSERT INTO `TrackElement_sensor` VALUES (351, 364);
INSERT INTO `Route_routeDefinition` VALUES (230, 364);
INSERT INTO `TrackElement` VALUES (365);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (365, 693);
INSERT INTO `TrackElement_sensor` VALUES (365, 364);
INSERT INTO `Sensor` (`id`) VALUES (366);
INSERT INTO `TrackElement_sensor` VALUES (351, 366);
INSERT INTO `Route_routeDefinition` VALUES (230, 366);
INSERT INTO `TrackElement` VALUES (367);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (367, 139);
INSERT INTO `TrackElement_sensor` VALUES (367, 366);
INSERT INTO `Sensor` (`id`) VALUES (368);
INSERT INTO `TrackElement_sensor` VALUES (351, 368);
INSERT INTO `Route_routeDefinition` VALUES (230, 368);
INSERT INTO `TrackElement` VALUES (369);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (369, 11);
INSERT INTO `TrackElement_sensor` VALUES (369, 368);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 351;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (370, 3, 351, 230);
INSERT INTO `TrackElement` VALUES (371);
INSERT INTO `Switch` (`id`) VALUES (371);
INSERT INTO `Sensor` (`id`) VALUES (372);
INSERT INTO `TrackElement_sensor` VALUES (371, 372);
INSERT INTO `Route_routeDefinition` VALUES (230, 372);
INSERT INTO `TrackElement` VALUES (373);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (373, -234);
INSERT INTO `TrackElement_sensor` VALUES (373, 372);
INSERT INTO `Sensor` (`id`) VALUES (374);
INSERT INTO `TrackElement_sensor` VALUES (371, 374);
INSERT INTO `Route_routeDefinition` VALUES (230, 374);
INSERT INTO `TrackElement` VALUES (375);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (375, 270);
INSERT INTO `TrackElement_sensor` VALUES (375, 374);
INSERT INTO `Sensor` (`id`) VALUES (376);
INSERT INTO `TrackElement_sensor` VALUES (371, 376);
INSERT INTO `Route_routeDefinition` VALUES (230, 376);
INSERT INTO `TrackElement` VALUES (377);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (377, 240);
INSERT INTO `TrackElement_sensor` VALUES (377, 376);
INSERT INTO `Sensor` (`id`) VALUES (378);
INSERT INTO `TrackElement_sensor` VALUES (371, 378);
INSERT INTO `Route_routeDefinition` VALUES (230, 378);
INSERT INTO `TrackElement` VALUES (379);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (379, 763);
INSERT INTO `TrackElement_sensor` VALUES (379, 378);
INSERT INTO `Sensor` (`id`) VALUES (380);
INSERT INTO `TrackElement_sensor` VALUES (371, 380);
INSERT INTO `Route_routeDefinition` VALUES (230, 380);
INSERT INTO `TrackElement` VALUES (381);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (381, 82);
INSERT INTO `TrackElement_sensor` VALUES (381, 380);
INSERT INTO `Sensor` (`id`) VALUES (382);
INSERT INTO `TrackElement_sensor` VALUES (371, 382);
INSERT INTO `TrackElement` VALUES (383);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (383, 350);
INSERT INTO `TrackElement_sensor` VALUES (383, 382);
INSERT INTO `Sensor` (`id`) VALUES (384);
INSERT INTO `TrackElement_sensor` VALUES (371, 384);
INSERT INTO `Route_routeDefinition` VALUES (230, 384);
INSERT INTO `TrackElement` VALUES (385);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (385, 508);
INSERT INTO `TrackElement_sensor` VALUES (385, 384);
INSERT INTO `Sensor` (`id`) VALUES (386);
INSERT INTO `TrackElement_sensor` VALUES (371, 386);
INSERT INTO `Route_routeDefinition` VALUES (230, 386);
INSERT INTO `TrackElement` VALUES (387);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (387, 674);
INSERT INTO `TrackElement_sensor` VALUES (387, 386);
INSERT INTO `Sensor` (`id`) VALUES (388);
INSERT INTO `TrackElement_sensor` VALUES (371, 388);
INSERT INTO `Route_routeDefinition` VALUES (230, 388);
INSERT INTO `TrackElement` VALUES (389);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (389, 823);
INSERT INTO `TrackElement_sensor` VALUES (389, 388);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 371;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (390, 1, 371, 230);
INSERT INTO `TrackElement` VALUES (391);
INSERT INTO `Switch` (`id`) VALUES (391);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 391;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (392, 3, 391, 230);
INSERT INTO `TrackElement` VALUES (393);
INSERT INTO `Switch` (`id`) VALUES (393);
INSERT INTO `Sensor` (`id`) VALUES (394);
INSERT INTO `TrackElement_sensor` VALUES (393, 394);
INSERT INTO `Route_routeDefinition` VALUES (230, 394);
INSERT INTO `TrackElement` VALUES (395);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (395, 168);
INSERT INTO `TrackElement_sensor` VALUES (395, 394);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 393;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (396, 3, 393, 230);
INSERT INTO `TrackElement` VALUES (397);
INSERT INTO `Switch` (`id`) VALUES (397);
INSERT INTO `Sensor` (`id`) VALUES (398);
INSERT INTO `TrackElement_sensor` VALUES (397, 398);
INSERT INTO `Route_routeDefinition` VALUES (230, 398);
INSERT INTO `TrackElement` VALUES (399);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (399, 725);
INSERT INTO `TrackElement_sensor` VALUES (399, 398);
UPDATE `Switch` SET `Switch_actualState` = 1 WHERE `id` = 397;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (400, 1, 397, 230);
INSERT INTO `TrackElement` VALUES (401);
INSERT INTO `Switch` (`id`) VALUES (401);
INSERT INTO `Sensor` (`id`) VALUES (402);
INSERT INTO `TrackElement_sensor` VALUES (401, 402);
INSERT INTO `Route_routeDefinition` VALUES (230, 402);
INSERT INTO `TrackElement` VALUES (403);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (403, 959);
INSERT INTO `TrackElement_sensor` VALUES (403, 402);
INSERT INTO `Sensor` (`id`) VALUES (404);
INSERT INTO `TrackElement_sensor` VALUES (401, 404);
INSERT INTO `Route_routeDefinition` VALUES (230, 404);
INSERT INTO `TrackElement` VALUES (405);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (405, -317);
INSERT INTO `TrackElement_sensor` VALUES (405, 404);
INSERT INTO `Sensor` (`id`) VALUES (406);
INSERT INTO `TrackElement_sensor` VALUES (401, 406);
INSERT INTO `Route_routeDefinition` VALUES (230, 406);
INSERT INTO `TrackElement` VALUES (407);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (407, 35);
INSERT INTO `TrackElement_sensor` VALUES (407, 406);
INSERT INTO `Sensor` (`id`) VALUES (408);
INSERT INTO `TrackElement_sensor` VALUES (401, 408);
INSERT INTO `Route_routeDefinition` VALUES (230, 408);
INSERT INTO `TrackElement` VALUES (409);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (409, 321);
INSERT INTO `TrackElement_sensor` VALUES (409, 408);
INSERT INTO `Sensor` (`id`) VALUES (410);
INSERT INTO `TrackElement_sensor` VALUES (401, 410);
INSERT INTO `Route_routeDefinition` VALUES (230, 410);
INSERT INTO `TrackElement` VALUES (411);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (411, 859);
INSERT INTO `TrackElement_sensor` VALUES (411, 410);
INSERT INTO `Sensor` (`id`) VALUES (412);
INSERT INTO `TrackElement_sensor` VALUES (401, 412);
INSERT INTO `Route_routeDefinition` VALUES (230, 412);
INSERT INTO `TrackElement` VALUES (413);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (413, 398);
INSERT INTO `TrackElement_sensor` VALUES (413, 412);
INSERT INTO `Sensor` (`id`) VALUES (414);
INSERT INTO `TrackElement_sensor` VALUES (401, 414);
INSERT INTO `Route_routeDefinition` VALUES (230, 414);
INSERT INTO `TrackElement` VALUES (415);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (415, 217);
INSERT INTO `TrackElement_sensor` VALUES (415, 414);
INSERT INTO `Sensor` (`id`) VALUES (416);
INSERT INTO `TrackElement_sensor` VALUES (401, 416);
INSERT INTO `Route_routeDefinition` VALUES (230, 416);
INSERT INTO `TrackElement` VALUES (417);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (417, 117);
INSERT INTO `TrackElement_sensor` VALUES (417, 416);
UPDATE `Switch` SET `Switch_actualState` = 0 WHERE `id` = 401;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (418, 3, 401, 230);
INSERT INTO `TrackElement` VALUES (419);
INSERT INTO `Switch` (`id`) VALUES (419);
INSERT INTO `Sensor` (`id`) VALUES (420);
INSERT INTO `TrackElement_sensor` VALUES (419, 420);
INSERT INTO `Route_routeDefinition` VALUES (230, 420);
INSERT INTO `TrackElement` VALUES (421);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (421, 50);
INSERT INTO `TrackElement_sensor` VALUES (421, 420);
INSERT INTO `Sensor` (`id`) VALUES (422);
INSERT INTO `TrackElement_sensor` VALUES (419, 422);
INSERT INTO `Route_routeDefinition` VALUES (230, 422);
INSERT INTO `TrackElement` VALUES (423);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (423, 723);
INSERT INTO `TrackElement_sensor` VALUES (423, 422);
INSERT INTO `Sensor` (`id`) VALUES (424);
INSERT INTO `TrackElement_sensor` VALUES (419, 424);
INSERT INTO `Route_routeDefinition` VALUES (230, 424);
INSERT INTO `TrackElement` VALUES (425);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (425, 295);
INSERT INTO `TrackElement_sensor` VALUES (425, 424);
INSERT INTO `Sensor` (`id`) VALUES (426);
INSERT INTO `TrackElement` VALUES (427);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (427, 706);
INSERT INTO `TrackElement_sensor` VALUES (427, 426);
INSERT INTO `Sensor` (`id`) VALUES (428);
INSERT INTO `TrackElement_sensor` VALUES (419, 428);
INSERT INTO `Route_routeDefinition` VALUES (230, 428);
INSERT INTO `TrackElement` VALUES (429);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (429, 612);
INSERT INTO `TrackElement_sensor` VALUES (429, 428);
INSERT INTO `Sensor` (`id`) VALUES (430);
INSERT INTO `TrackElement_sensor` VALUES (419, 430);
INSERT INTO `Route_routeDefinition` VALUES (230, 430);
INSERT INTO `TrackElement` VALUES (431);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (431, -624);
INSERT INTO `TrackElement_sensor` VALUES (431, 430);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 419;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (432, 0, 419, 230);
INSERT INTO `TrackElement` VALUES (433);
INSERT INTO `Switch` (`id`) VALUES (433);
INSERT INTO `Sensor` (`id`) VALUES (434);
INSERT INTO `TrackElement` VALUES (435);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (435, 554);
INSERT INTO `TrackElement_sensor` VALUES (435, 434);
INSERT INTO `Sensor` (`id`) VALUES (436);
INSERT INTO `TrackElement_sensor` VALUES (433, 436);
INSERT INTO `Route_routeDefinition` VALUES (230, 436);
INSERT INTO `TrackElement` VALUES (437);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (437, 776);
INSERT INTO `TrackElement_sensor` VALUES (437, 436);
UPDATE `Switch` SET `Switch_actualState` = 2 WHERE `id` = 433;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (438, 1, 433, 230);
INSERT INTO `TrackElement` VALUES (439);
INSERT INTO `Switch` (`id`) VALUES (439);
INSERT INTO `Sensor` (`id`) VALUES (440);
INSERT INTO `TrackElement_sensor` VALUES (439, 440);
INSERT INTO `Route_routeDefinition` VALUES (230, 440);
INSERT INTO `TrackElement` VALUES (441);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (441, 584);
INSERT INTO `TrackElement_sensor` VALUES (441, 440);
INSERT INTO `Sensor` (`id`) VALUES (442);
INSERT INTO `TrackElement_sensor` VALUES (439, 442);
INSERT INTO `Route_routeDefinition` VALUES (230, 442);
INSERT INTO `TrackElement` VALUES (443);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (443, 286);
INSERT INTO `TrackElement_sensor` VALUES (443, 442);
INSERT INTO `Sensor` (`id`) VALUES (444);
INSERT INTO `TrackElement_sensor` VALUES (439, 444);
INSERT INTO `Route_routeDefinition` VALUES (230, 444);
INSERT INTO `TrackElement` VALUES (445);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (445, 105);
INSERT INTO `TrackElement_sensor` VALUES (445, 444);
INSERT INTO `Sensor` (`id`) VALUES (446);
INSERT INTO `TrackElement_sensor` VALUES (439, 446);
INSERT INTO `Route_routeDefinition` VALUES (230, 446);
INSERT INTO `TrackElement` VALUES (447);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (447, 261);
INSERT INTO `TrackElement_sensor` VALUES (447, 446);
INSERT INTO `Sensor` (`id`) VALUES (448);
INSERT INTO `TrackElement_sensor` VALUES (439, 448);
INSERT INTO `TrackElement` VALUES (449);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (449, 300);
INSERT INTO `TrackElement_sensor` VALUES (449, 448);
INSERT INTO `Sensor` (`id`) VALUES (450);
INSERT INTO `TrackElement_sensor` VALUES (439, 450);
INSERT INTO `Route_routeDefinition` VALUES (230, 450);
INSERT INTO `TrackElement` VALUES (451);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (451, 253);
INSERT INTO `TrackElement_sensor` VALUES (451, 450);
INSERT INTO `Sensor` (`id`) VALUES (452);
INSERT INTO `TrackElement_sensor` VALUES (439, 452);
INSERT INTO `Route_routeDefinition` VALUES (230, 452);
INSERT INTO `TrackElement` VALUES (453);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (453, -145);
INSERT INTO `TrackElement_sensor` VALUES (453, 452);
INSERT INTO `Sensor` (`id`) VALUES (454);
INSERT INTO `TrackElement_sensor` VALUES (439, 454);
INSERT INTO `Route_routeDefinition` VALUES (230, 454);
INSERT INTO `TrackElement` VALUES (455);
INSERT INTO `Segment` (`id`, `Segment_length`) VALUES (455, 937);
INSERT INTO `TrackElement_sensor` VALUES (455, 454);
UPDATE `Switch` SET `Switch_actualState` = 3 WHERE `id` = 439;
INSERT INTO `SwitchPosition` (`id`, `SwitchPosition_switchState`, `SwitchPosition_switch`, `Route_switchPosition`) VALUES (456, 3, 439, 230);
INSERT INTO `TrackElement_connectsTo` VALUES (231, 233);
INSERT INTO `TrackElement_connectsTo` VALUES (233, 235);
INSERT INTO `TrackElement_connectsTo` VALUES (235, 237);
INSERT INTO `TrackElement_connectsTo` VALUES (237, 239);
INSERT INTO `TrackElement_connectsTo` VALUES (239, 241);
INSERT INTO `TrackElement_connectsTo` VALUES (241, 243);
INSERT INTO `TrackElement_connectsTo` VALUES (243, 245);
INSERT INTO `TrackElement_connectsTo` VALUES (245, 247);
INSERT INTO `TrackElement_connectsTo` VALUES (247, 249);
INSERT INTO `TrackElement_connectsTo` VALUES (249, 251);
INSERT INTO `TrackElement_connectsTo` VALUES (251, 253);
INSERT INTO `TrackElement_connectsTo` VALUES (253, 255);
INSERT INTO `TrackElement_connectsTo` VALUES (255, 257);
INSERT INTO `TrackElement_connectsTo` VALUES (257, 259);
INSERT INTO `TrackElement_connectsTo` VALUES (259, 261);
INSERT INTO `TrackElement_connectsTo` VALUES (261, 263);
INSERT INTO `TrackElement_connectsTo` VALUES (263, 265);
INSERT INTO `TrackElement_connectsTo` VALUES (265, 267);
INSERT INTO `TrackElement_connectsTo` VALUES (267, 269);
INSERT INTO `TrackElement_connectsTo` VALUES (269, 271);
INSERT INTO `TrackElement_connectsTo` VALUES (271, 273);
INSERT INTO `TrackElement_connectsTo` VALUES (273, 275);
INSERT INTO `TrackElement_connectsTo` VALUES (275, 277);
INSERT INTO `TrackElement_connectsTo` VALUES (277, 279);
INSERT INTO `TrackElement_connectsTo` VALUES (279, 281);
INSERT INTO `TrackElement_connectsTo` VALUES (281, 283);
INSERT INTO `TrackElement_connectsTo` VALUES (283, 285);
INSERT INTO `TrackElement_connectsTo` VALUES (285, 287);
INSERT INTO `TrackElement_connectsTo` VALUES (287, 289);
INSERT INTO `TrackElement_connectsTo` VALUES (289, 291);
INSERT INTO `TrackElement_connectsTo` VALUES (291, 293);
INSERT INTO `TrackElement_connectsTo` VALUES (293, 295);
INSERT INTO `TrackElement_connectsTo` VALUES (295, 297);
INSERT INTO `TrackElement_connectsTo` VALUES (297, 299);
INSERT INTO `TrackElement_connectsTo` VALUES (299, 301);
INSERT INTO `TrackElement_connectsTo` VALUES (301, 303);
INSERT INTO `TrackElement_connectsTo` VALUES (303, 305);
INSERT INTO `TrackElement_connectsTo` VALUES (305, 307);
INSERT INTO `TrackElement_connectsTo` VALUES (307, 309);
INSERT INTO `TrackElement_connectsTo` VALUES (309, 311);
INSERT INTO `TrackElement_connectsTo` VALUES (311, 313);
INSERT INTO `TrackElement_connectsTo` VALUES (313, 315);
INSERT INTO `TrackElement_connectsTo` VALUES (315, 317);
INSERT INTO `TrackElement_connectsTo` VALUES (317, 319);
INSERT INTO `TrackElement_connectsTo` VALUES (319, 321);
INSERT INTO `TrackElement_connectsTo` VALUES (321, 323);
INSERT INTO `TrackElement_connectsTo` VALUES (323, 325);
INSERT INTO `TrackElement_connectsTo` VALUES (325, 327);
INSERT INTO `TrackElement_connectsTo` VALUES (327, 329);
INSERT INTO `TrackElement_connectsTo` VALUES (329, 331);
INSERT INTO `TrackElement_connectsTo` VALUES (331, 333);
INSERT INTO `TrackElement_connectsTo` VALUES (333, 335);
INSERT INTO `TrackElement_connectsTo` VALUES (335, 337);
INSERT INTO `TrackElement_connectsTo` VALUES (337, 339);
INSERT INTO `TrackElement_connectsTo` VALUES (339, 341);
INSERT INTO `TrackElement_connectsTo` VALUES (341, 343);
INSERT INTO `TrackElement_connectsTo` VALUES (343, 345);
INSERT INTO `TrackElement_connectsTo` VALUES (345, 347);
INSERT INTO `TrackElement_connectsTo` VALUES (347, 349);
INSERT INTO `TrackElement_connectsTo` VALUES (349, 351);
INSERT INTO `TrackElement_connectsTo` VALUES (351, 353);
INSERT INTO `TrackElement_connectsTo` VALUES (353, 355);
INSERT INTO `TrackElement_connectsTo` VALUES (355, 357);
INSERT INTO `TrackElement_connectsTo` VALUES (357, 359);
INSERT INTO `TrackElement_connectsTo` VALUES (359, 361);
INSERT INTO `TrackElement_connectsTo` VALUES (361, 363);
INSERT INTO `TrackElement_connectsTo` VALUES (363, 365);
INSERT INTO `TrackElement_connectsTo` VALUES (365, 367);
INSERT INTO `TrackElement_connectsTo` VALUES (367, 369);
INSERT INTO `TrackElement_connectsTo` VALUES (369, 371);
INSERT INTO `TrackElement_connectsTo` VALUES (371, 373);
INSERT INTO `TrackElement_connectsTo` VALUES (373, 375);
INSERT INTO `TrackElement_connectsTo` VALUES (375, 377);
INSERT INTO `TrackElement_connectsTo` VALUES (377, 379);
INSERT INTO `TrackElement_connectsTo` VALUES (379, 381);
INSERT INTO `TrackElement_connectsTo` VALUES (381, 383);
INSERT INTO `TrackElement_connectsTo` VALUES (383, 385);
INSERT INTO `TrackElement_connectsTo` VALUES (385, 387);
INSERT INTO `TrackElement_connectsTo` VALUES (387, 389);
INSERT INTO `TrackElement_connectsTo` VALUES (389, 391);
INSERT INTO `TrackElement_connectsTo` VALUES (391, 393);
INSERT INTO `TrackElement_connectsTo` VALUES (393, 395);
INSERT INTO `TrackElement_connectsTo` VALUES (395, 397);
INSERT INTO `TrackElement_connectsTo` VALUES (397, 399);
INSERT INTO `TrackElement_connectsTo` VALUES (399, 401);
INSERT INTO `TrackElement_connectsTo` VALUES (401, 403);
INSERT INTO `TrackElement_connectsTo` VALUES (403, 405);
INSERT INTO `TrackElement_connectsTo` VALUES (405, 407);
INSERT INTO `TrackElement_connectsTo` VALUES (407, 409);
INSERT INTO `TrackElement_connectsTo` VALUES (409, 411);
INSERT INTO `TrackElement_connectsTo` VALUES (411, 413);
INSERT INTO `TrackElement_connectsTo` VALUES (413, 415);
INSERT INTO `TrackElement_connectsTo` VALUES (415, 417);
INSERT INTO `TrackElement_connectsTo` VALUES (417, 419);
INSERT INTO `TrackElement_connectsTo` VALUES (419, 421);
INSERT INTO `TrackElement_connectsTo` VALUES (421, 423);
INSERT INTO `TrackElement_connectsTo` VALUES (423, 425);
INSERT INTO `TrackElement_connectsTo` VALUES (425, 427);
INSERT INTO `TrackElement_connectsTo` VALUES (427, 429);
INSERT INTO `TrackElement_connectsTo` VALUES (429, 431);
INSERT INTO `TrackElement_connectsTo` VALUES (431, 433);
INSERT INTO `TrackElement_connectsTo` VALUES (433, 435);
INSERT INTO `TrackElement_connectsTo` VALUES (435, 437);
INSERT INTO `TrackElement_connectsTo` VALUES (437, 439);
INSERT INTO `TrackElement_connectsTo` VALUES (439, 441);
INSERT INTO `TrackElement_connectsTo` VALUES (441, 443);
INSERT INTO `TrackElement_connectsTo` VALUES (443, 445);
INSERT INTO `TrackElement_connectsTo` VALUES (445, 447);
INSERT INTO `TrackElement_connectsTo` VALUES (447, 449);
INSERT INTO `TrackElement_connectsTo` VALUES (449, 451);
INSERT INTO `TrackElement_connectsTo` VALUES (451, 453);
INSERT INTO `TrackElement_connectsTo` VALUES (453, 455);
INSERT INTO `TrackElement_connectsTo` VALUES (228, 231);
INSERT INTO `TrackElement_connectsTo` VALUES (455, 4);
COMMIT;
CREATE INDEX Segment_idx_length ON Segment (Segment_length);
CREATE INDEX Route_routeDefinition_idx ON Route_routeDefinition (Route_id, Sensor_id);
CREATE INDEX Sensor_trackElement_idx1 ON TrackElement_sensor (TrackElement_id);
CREATE INDEX Sensor_trackElement_idx2 ON TrackElement_sensor (Sensor_id);
